services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: computer_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/workspaces/computer-inventory-app
    working_dir: /workspaces/computer-inventory-app/backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URL=mongodb://db:27017/computer_inventory
      - JWT_SECRET=YOUR_OWN_SECRET_LOVE
    depends_on:
      - db
    command: sleep infinity
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: computer_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/workspaces/computer-inventory-app
    working_dir: /workspaces/computer-inventory-app/frontend
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    command: sleep infinity
    stdin_open: true
    tty: true

  db:
    image: mongo:7
    container_name: computer_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  